### ISSUE TITLE
Problems with 'pet'

### ISSUE THREAD

**Issue by rjfnobre** [bondhugula/pluto#14]
I tried to compile the 'pet' branch, but I get the following errors:
 
 CXXLD    pet_check_code
./.libs/libpet.so: undefined reference to `clang::DeclarationName::getAsString[abi:cxx11]() const'
./.libs/libpet.so: undefined reference to `llvm::sys::getDefaultTargetTriple[abi:cxx11]()'
./.libs/libpet.so: undefined reference to `clang::getClangFullVersion[abi:cxx11]()'
./.libs/libpet.so: undefined reference to `clang::DeclarationNameInfo::getAsString[abi:cxx11]() const'
./.libs/libpet.so: undefined reference to `clang::QualType::getAsString[abi:cxx11](clang::Type const*, clang::Qualifiers)'
collect2: error: ld returned 1 exit status
Makefile:888: recipe for target 'pet_check_code' failed

I tried both with Clang 3.4 and Clang 3.3 as it says in the front-page Readme that it only works with versions up to 3.4.

Should I use a different version of Clang?
Which one?

Thanks in advance!

**Comment by bondhugula** [comment]
> Should I use a different version of Clang?

No, 3.4 should have worked. 

Just to confirm; what's the output of your 

$ llvm-config --version

And what's your g++ version?

**Comment by bondhugula** [comment]
Also, is the version of gcc/g++ you are using now different from the one used for building llvm/clang? Did you update gcc/g++ after installing llvm/clang?

**Comment by rjfnobre** [comment]
$llvm-config --version
3.4

I used the pre-built version of clang 3.4 from http://releases.llvm.org/download.html

gcc/g++ is the one that comes with ubuntu 16.04.

**Comment by rjfnobre** [comment]
In case I build a new instance of Clang from source using the system's default gcc/g++, should I do it with Clang 3.4, 3.4.1, or 3.4.2?

**Comment by rjfnobre** [comment]
I managed to compile it.

I compiled LLVM and Clang 3.4 from source and used that version alongside with Pluto.

**Comment by bondhugula** [comment]
> In case I build a new instance of Clang from source using the system's default gcc/g++, 
> should I do it with Clang 3.4, 3.4.1, or 3.4.2?

Clang 3.4. 

Could you build from sources? This is what I've always done.

**Comment by bondhugula** [comment]
> I managed to compile it.
> 
> I compiled LLVM and Clang 3.4 from source and used that version alongside with Pluto.

So pet and pluto builds fine with this?
